#!/usr/bin/env python
from __future__ import absolute_import, division, print_function
# import os
import roslaunch
import sys


def print_node_info(node):
    for var in ('package',
                'type',
                'name',
                'namespace',
                'machine_name',
                'args',
                'remap_args',
                'env_args',
                'filename'):
        print('%s: %s' % (var, node.__getattribute__(var)))


def apply_tmux_prefix(node):
    if node.launch_prefix:
        # print('[ros_tmux] Overriding launch prefix "%s" for node %s.'
        #       % (node.launch_prefix, node.name))
        print('[ros_tmux] Prefixing launch prefix "%s" for node %s.'
              % (node.launch_prefix, node.name))
        node.launch_prefix = 'ros_tmux_run %s' % node.launch_prefix
        return
    node.launch_prefix = 'ros_tmux_run '


def use_screen_output(node):
    if node.output == 'log':
        print('[ros_tmux] Overriding output %s for node %s.'
              % (node.output, node.name))
    node.output = 'screen'


def set_env(node):
    # Forward ROS_NAMESPACE in args.
    node.args = node.args or ''
    node.args = '%s %s:=%s' % (node.args, '__ns', node.namespace)


def adjust_nodes(nodes):
    for node in nodes:
        # print_node_info(node)
        apply_tmux_prefix(node)
        set_env(node)
        use_screen_output(node)


uuid = roslaunch.rlutil.get_or_generate_uuid(None, False)
roslaunch.configure_logging(uuid)

# Resolve <package> <launch> arguments.
launch_paths = roslaunch.rlutil.resolve_launch_arguments(sys.argv[1:])
launch = roslaunch.parent.ROSLaunchParent(uuid, launch_paths)

# Start infrastructure in advance to parse the launch file into config.
# (From the code, running it repeatedly seems to be safe.)
launch._load_config()
adjust_nodes(launch.config.nodes)

# Parse the launch file (done), start roscore and nodes, advertise topics.
# Nothing is published yet. (No handshake until spin?)
launch.start()

try:
    launch.spin()
finally:
    # After Ctrl+C, stop all nodes from running
    launch.shutdown()
